aws_region = "ca-central-1"
aws_deployment_role = "arn:aws:iam::860568434255:role/station_deploy_dev"
object_prefix = "station.dev."
webclient_stage = "DEVELOPMENT"
source_repository = "https://github.com/kiyote/Station"
source_repository_branch = "main"