name: Containerize

on:
  pull_request:
    paths:
    - 'docker-compose.yml'
    - 'Dockerfile'
    - '.github/workflows/containerize.yml'

  workflow_dispatch:
    inputs:
      push:
        description: 'Whether or not to push the docker image.'
        required: true
        default: 'false'

jobs:
    build:
        steps:
          - uses: actions/checkout@v3
          
          - name: Build
            run: |
              docker build \
                --no-cache \
                --tag image .