name: Containerize

on:
  pull_request:
    paths:
    - 'docker-compose.yml'
    - 'Dockerfile'
    - '.github/workflows/containerize.yml'

  workflow_dispatch:
    inputs:
      push:
        description: 'Whether or not to push the docker image.'
        required: true
        default: 'false'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v3
          
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              role-to-assume: arn:aws:iam::860568434255:role/station_deploy_dev
              aws-region: ca-central-1

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1

          - name: Build, tag, and push docker image to Amazon ECR
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              REPOSITORY: "station.dev.server"
              IMAGE_TAG: ${{ github.sha }}-build${{ github.run_number }}
            run: |
              docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
              docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG