name: Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.3.1
  PLAN_DIR: "${{ github.workspace }}"

jobs:
  dev:
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
           terraform_version: ${{ env.TERRAFORM_VERSION }}
        working-directory: terraform/environments/dev
        run: |
          terraform init
          terraform destroy -target=station.dev.app_role